/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function ocr(buffer: Buffer): Array<OcrResult>

export interface OcrResult {
  bbox: Array<[number, number]>
  content: string
}

export declare function plus100(input: number): number
